name: catering_app
description: "Catering app."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.4.0
  jwt_decoder: ^2.0.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  html: ^0.15.5
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "web/icons/Icon-512.png"

flutter:
  uses-material-design: true