name: catering_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  intl: ^0.20.2
  image_picker: ^1.1.2
  shared_preferences: ^2.2.3
  go_router: ^17.0.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.0
  google_fonts: ^6.3.2

  graphql_flutter: ^5.2.1
  flutter_hooks: ^0.21.3+1
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  graphql_codegen: ^3.0.0

  # rules and activating additional ones.
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
